services:
  app:
    build: .
    ports:
      - "4173:4173"
    env_file:
      - .env  # Load .env file if preferred
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb?schema=public
      - NODE_ENV=development
      - PORT=3000
      - S3_ENDPOINT=http://minio:9000
      - S3_BUCKET=gcode-vault
      - S3_ACCESS_KEY_ID=admin
      - S3_SECRET_ACCESS_KEY=password123
    depends_on:
      - db
      - minio


  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  minio:
    image: quay.io/minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000" # S3 API Port
      - "9001:9001" # Web Console Port
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: password123 # Change this!
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    restart: unless-stopped

  # Optional: Automatically create a bucket called 'gcode-vault' on startup
  createbuckets:
    image: quay.io/minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      sleep 5;
      /usr/bin/mc alias set local_s3 http://minio:9000 admin password123;
      /usr/bin/mc mb local_s3/gcode-vault;
      exit 0;
      "



volumes:
  postgres_data:


